### ISSUE TITLE
Argument : ✔️Issue 결제 처리 방식과 이에 대한 DB 설계 방법

### ISSUE THREAD

**Issue by RTUnu12** [UFO-System/ufo-backend#5]
## 논의 주제
DB에 결제 API로부터 받은 정보인 입금자 명과 입금 금액을 저장할 필드를 만들 것인가?

## 배경
API가 입금자명과 입금금액을 실시간으로 보내는지, 아니면 이전 데이터를 포함해서 보내는지 모름

## 논의하고자 하는 내용
즉, 현재 사용할 API가 입금자명과 입금금액 등 결제에 대한 정보를 언제 보내주고 이를 어떻게 DB의 정보와 합쳐 처리하고자 할 것인지에 따라 결제 정보를 저장할 필드나 테이블을 만들거나 따로 저장할 공간을 DB에서 만들지 않고 백엔드에서 DB의 정보와 합쳐 프론트로 보낼 것인지를 결정해야합니다.

## 제안된 아이디어
만약 API가 이전 데이터를 포함해서 보내주면 다음 처리방식이 가능
: 프론트에서 주문할 것들 주문하기
-> DB의 주문 테이블에 저장
-> 거기서 계좌 뜨고 보내면
-> 서버가 이 결제 정보와 주문 테이블을 조합해서 프론트로 전달
즉, 필드를 따로 지정하지 않아도 됨

## 추가 정보
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/4684f010-45a9-4a9a-a85d-8845458531e1)
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/03ac3864-c8e7-417f-95dc-4957b689d64b)

## 결론 도출을 위한 질문
1. API가 어느 시기에 결제 정보를 보내는가?
2. 백엔드는 이를 어떻게 처리할 것인가?

**Comment by genwo123** [comment]
API를 작업하고 있는 팀이 테스트를 해보고 코멘트를 달아주면 좋을 것 같네요! 확실하진 않지만 전에 회의에서 들었을때 결제 정보는 실시간으로 전달된다고 들었습니다!

**Comment by RTUnu12** [comment]
그러면 이 부분은 API의 테스트가 완료될 때 결정하면 될 거 같습니다.

**Comment by YoungJae730** [comment]
API의 구조로 보았을때 은행의 입출금 알림 서비스를 통해 SMS 메시지가 수신될 경우 그 메시지의 정보를 이용해서 데이터를 서버로 보내주는 시스템이므로 이전 데이터가 아닌 현재 데이터만 날라올 것 같네요 따로 DB나 서버에서 저장해야 할 것 같습니다.
