### ISSUE TITLE
Argument : ✔️Issue : DB 구조 설계 : 이미지 저장 방법

### ISSUE THREAD

**Issue by RTUnu12** [UFO-System/ufo-backend#6]
## 논의 주제
DB에서 이미지를 어떠한 방식으로 저장할 것인가?

## 배경
프론트엔드에서 메뉴에 상당히 많은 양의 이미지를 필요로 합니다. 게다가 추가 삭제도 메뉴에 따라 많이 일어나게 됩니다.
그러기에 이미지의 처리 방법에 따라 전체 성능의 차이가 확연하게 나타날 것이기에 이를 논의합니다. 

## 논의하고자 하는 내용
현재 이미지를 저장하는 대표적인 방법은 다음과 같습니다.

1. 이미지 자체를 BLOB로 변환하여 DB에 저장
: 구현하기가 간편하고, 프론트앤드는 다시 이 BLOB를 복호화하여 불러오기만 하면 됩니다
: 하지만 DB에 심각한 성능 저하를 불러올 수 있으며 특히 이 프로젝트는 이미지가 들어갈 메뉴의 추가 삭제가 일어나며 그 양 또한 많기에 적합하지 않은 방법입니다.

2. 서버의 로컬 파일 시스템에 파일을 직접 저장 후 DB는 경로로 이미지를 불러옴
: 위처럼 간편하고, 프론트앤드는 복호화할 필요도 없습니다.
: 하지만 서버의 부담이 심해집니다. 특히 여러 관리자가 이를 사용할 경우 서버의 심각한 성능 저하를 불러일으킬 것입니다.

3. Amazon S3같은 클라우드 서비스에 이미지 저장 후 DB는 링크로 이미지를 불러옴 (제가 추천하는 방법)
: 클라우드 서비스 비용이 필요합니다.
: DB 측에서 구현할 것들이 많습니다.
: 하지만 가장 안전하고, 성능 저하가 생기지 않습니다.

4. 콘텐츠 전송 네트워크 (CDN) 사용
: 서버, DB의 성능 저하가 없으며, 가장 안정적입니다.
: 다만 너무 과하게 어렵습니다.

## 제안된 아이디어
저희 프로젝트는 이미지의 추가 및 삭제가 빈번할 것이기에 시간이 걸리는 한이 있더라도 3번 방법을 실행하는 것을 추천합니다.

## 추가 정보
https://medium.com/@hassaanistic/best-way-to-store-image-in-any-web-application-development-best-practices-and-considerations-4fbacdf066d2

https://www.beekeeperstudio.io/blog/how-to-store-images-in-a-database

## 결론 도출을 위한 질문
1. 저 방법 외에 더 좋은 방법이 있습니까?
2. 지금 시스템의 특성, 특히 이미지에 대해 얼마나 많은 중요도를 가지고 있습니까?

**Comment by genwo123** [comment]
1. AWS 방식이 제일 좋다고 생각합니다. 그 외에는 조금 더 생각해보겠습니다.
2. 현재 이미지가 얼마나 영향이 있는지는 다음 회의까지 준비해서 답변드려보겠습니다

**Comment by RTUnu12** [comment]
1. 혹시 AWS에 대한 요금 처리는 어떻게 할 생각이십니까?
2. 알겠습니다. 그 영향에 따라 세부적으로 결정해야겠네요.

**Comment by RTUnu12** [comment]
논의 결과 굳이 이미지를 추가하지 않아도 될 것 같습니다. 부스를 열 때 음식에 이미지를 추가하거나 하진 않을 것 같습니다.
