### ISSUE TITLE
Argument : ✔️Issue : DB 완성, 구조에 대한 논의

### ISSUE THREAD

**Issue by RTUnu12** [UFO-System/ufo-backend#7]
## 논의 주제
1. API로부터 받아오는 정보는 "입금정보"라는 테이블에 저장, 이를 외래키로 하여 주문 테이블로 관계 맺음 -> 적당한가요?
2. 전체적인 구조에 대한 논의가 필요합니다.

## 배경
이제 통합하여 테스트할 예정이기에 논의를 해야할 것 같습니다.

## 논의하고자 하는 내용
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/e6d60031-ce50-4627-a33d-f83546d24193)

* 해당 구조를 보고 만약 건의사항이 있으면 댓글로 달아주세요.
* 또한 API 팀은 "입금정보" 테이블 구조를 보시고 판단해주세요.

**Comment by YoungJae730** [comment]
잘 만들어졌네요! 다만 의문점이 있습니다.
1. 관리자 테이블에는 은행이름이, 입금 정보에는 계좌번호가 빠진것 같습니다. 
2. 주문이 들어왔을때 주문하기 전 미리 입금을 하지 않았다면 입금 정보가 없을텐데 그럼 주문테이블의 입금id처리 방식은 어떻게 되나요? 또한 나중에 들어왔을 경우 이를 서버에서 주문에 추가하는 걸까요?
3. 주문과 청구가 1대1 대응이면 한 주문엔 한 가지의 음식만 주문할 수 있을까요?

**Comment by RTUnu12** [comment]
1. 알겠습니다. 추가하겠습니다.
2. 그 부분은 조금 더 판단해봐야겠네요.
3. 사실 1대1대N, 즉 (주문-청구-<아이템) 관계인데, 주문과 아이템의 관계가 1:N이다보니 이를 구현하기 위해 했습니다. 이 부분도 논의 및 설계에 따라 조정하겠습니다.

**Comment by RTUnu12** [comment]
@YoungJae730 
3. 테이블 수정하였습니다.
프론트앤드에서 주문 시, 주문 자체(음식 미포함)이 먼저 포함되고 그 다음 음식들을 아이템 테이블에 추가하여 거기에 외래키로 주문ID를 구성하여 1:N관계를 이루었습니다.
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/0fc27cb3-0329-481a-8ee9-7e7d46cefc10)

**Comment by RTUnu12** [comment]
@YoungJae730 
2. 원래 테이블은 주문에 입금id가 외래키로 있는 구조여서 주문이 입금에 종속적이였기에 제시하신 문제에 대해 해결하지 못하는 경향이 있습니다. 그러기에 종속적 관계를 바꾸어 입금 테이블에 주문id가 들어가는 식으로 하여 주문 먼저하고 입금하는 방식에 문제가 없게 하였습니다. 혹시 다른 문제점이 있으신가요?
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/be33a2f8-ebf0-4153-9547-ccdeffee37e3)

**Comment by Sonwon112** [comment]
테이블 구조를 살펴보았는데 저희 시스템에서 입금 정보를 저장해야할 이유가 있을까요?
제가 생각하기에 입금정보는 백엔드 부분에서 사용되고 그 이후에 다른 곳에서 사용될 필요가 없다고 판단됩니다. 이 부분은 의논을 해보아야할 거 같아요.

**Comment by RTUnu12** [comment]
@Sonwon112 
1. 백엔드팀의 요청
2. 만약 API가 서버와 바로 연결된다면 말하신대로 DB와 API 정보를 서버에서 조합하면 되기에 굳이 DB로 갈 이유는 없을 것 같긴 합니다. 하지만 입금을 잘못했다던가, 그 외 오류가 생겼을 때를 대비해야 하기 때문에 입금 정보를 저장합니다.

**Comment by YoungJae730** [comment]
@RTUnu12 
그럼 서버사이드에서 api로 입금 내역을 받아왔을때 이를 db에 저장하기 위해 주문 id를 식별하는 방법은 어떤걸까요?

**Comment by Sonwon112** [comment]
@RTUnu12 
오류 발생시를 대비해서 저장을 한다면 다른 테이블과 관계를 맺을 필요없이 단순이 입금 내역만 저장하는 테이블로 분리해두는게 좋을거 같다고 생각이 드네요 의논은 한번 필요할거 같아요

**Comment by RTUnu12** [comment]
@Sonwon112 @YoungJae730 
말씀하신 대로 결제 테이블을 분리하여 비상시에 활용할 테이블로만 사용하게 하였습니다.
![image](https://github.com/UFO-System/ufo-backend/assets/73762862/0864096a-0358-4d0b-9179-d8d39e73458a)
